# Generated by Django 4.2.18 on 2025-02-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pin_created_at_pin_user_alter_board_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
